# Generated by Django 5.2.6 on 2025-09-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_vote_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poll",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="vote",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
